std_msgs/Header header

uint8 f_shift
uint8 f_shift1
float64 fDeForwardVel
float64 fFLRWheelAverAngle

#vehicle speed
float64 fForwardVel

float64 petral_pressure
float64 pressure_back
float64 FrontLeftWheelSpeed
float64 FrontRightWheelSpeed
float64 BackLeftWheelSpeed
float64 BackRightWheelSpeed

float64 motor_I_L
float64 motor_I_R
float64 motor_Torque_L
float64 motor_Torque_R
float64 motor_U_L
float64 motor_U_R
float64 motor_n_now_L
float64 motor_n_now_R
float64 Gear_state_now
float64 steer_degree_now
float64 steer_direction_now
float64 soc_now
