float64        center_x             
float64        center_y             
float64        object_width         
float64        object_length        
float64        object_high          

float64          object_rect_x
float64          object_rect_y
float64          object_rect_width
float64          object_rect_height 

float64        x_src                
float64        y_src                
float64        v_x                  
float64        v_y               
float64        v                   
float64        v_theta
float64        pos_heading         
float64        v_w                  

int32          trackpoint32_index
int32          filter_method

bool         is_updated           
int32          time_stamp           
int32          ID_number                   
int32          confidence_level    
int32          tracked_times        
int32          miss_tracked_times   

int32          dis_veh_xy
int32          position_orientation 
int32          occluded_state       
int32          object_type        
int32          dangerous_level  
float64        trackpoint_index    
